# It's good practice to include the Pod source in your Podfile
source 'https://github.com/CocoaPods/Specs.git'

# specify platform and target OS version
platform :ios, '13.0'

inhibit_all_warnings!

target 'NanToolboxDemo' do
  use_frameworks!

  pod 'Alamofire'  # 网络请求
  pod 'SSZipArchive'  # 使用SSZipArchive替代ZipArchive
end

target 'NanToolboxDemoTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # 添加以下设置以解决libarclite问题
      config.build_settings['CLANG_ENABLE_MODULE_DEBUGGING'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end


