# It's good practice to include the Pod source in your Podfile
#source 'https://github.com/CocoaPods/Specs.git'

# specify platform and target OS version
platform :ios, '13.0'

inhibit_all_warnings!

target 'NanToolboxDemo' do
  use_frameworks!

  pod 'Alamofire' # 网络请求
  pod 'ZipArchive' # ZIP压缩
end

target 'NanToolboxDemoTests' do
  use_frameworks!
  
  # 测试target专用的pod依赖
  
end


